import {useCallback,useEffect,useMemo,useRef,useState} from "react";

type Kind="video"|"audio";
type Clip={id:string;track:number;kind:Kind;name:string;start:number;duration:number;color:string;url?:string};
type Snap={clips:Clip[];playhead:number;zoom:number};
const FPS=30, MIN=.08, colors=["#4c82b4","#708e49","#b4763d","#725b98","#3d8882","#9b5367"];
const seed:Clip[]=[
{id:"v1",track:0,kind:"video",name:"CAM_001.mp4",start:0,duration:8.4,color:colors[0]},
{id:"v2",track:0,kind:"video",name:"CAM_002.mp4",start:8.7,duration:5.8,color:colors[1]},
{id:"v3",track:0,kind:"video",name:"BROLL_ROAD.mp4",start:14.8,duration:7.2,color:colors[3]},
{id:"a1",track:1,kind:"audio",name:"CAM_001.wav",start:0,duration:14.5,color:colors[2]},
{id:"a2",track:1,kind:"audio",name:"MUSIC_BED.wav",start:0,duration:24,color:colors[4]}];
const id=()=>Math.random().toString(36).slice(2,9);
const tc=(x:number)=>{x=Math.max(0,x);const f=Math.floor(x%1*FPS),s=Math.floor(x)%60,m=Math.floor(x/60)%60,h=Math.floor(x/3600);return [h,m,s].map(v=>String(v).padStart(2,"0")).join(":")+":"+String(f).padStart(2,"0")};
function Row({name,value}:{name:string;value:string}){return <div className="row"><span>{name}</span><output>{value}</output><i>◆</i></div>}

export default function App(){
 const [clips,setClips]=useState<Clip[]>(seed),[selected,setSelected]=useState("v1"),[playhead,setPlayhead]=useState(3.1);
 const [playing,setPlaying]=useState(false),[zoom,setZoom]=useState(52),[tool,setTool]=useState<"select"|"razor">("select"),[snap,setSnap]=useState(true);
 const [history,setHistory]=useState<Snap[]>([]),[future,setFuture]=useState<Snap[]>([]),[drag,setDrag]=useState<string|null>(null);
 const input=useRef<HTMLInputElement>(null),last=useRef(performance.now()),pps=zoom;
 const total=useMemo(()=>Math.max(30,...clips.map(c=>c.start+c.duration+3)),[clips]);
 const save=useCallback(()=>{setHistory(h=>[...h.slice(-49),{clips:clips.map(c=>({...c})),playhead,zoom}]);setFuture([])},[clips,playhead,zoom]);
 const undo=useCallback(()=>{setHistory(h=>{const s=h.at(-1);if(!s)return h;setFuture(f=>[{clips:clips.map(c=>({...c})),playhead,zoom},...f]);setClips(s.clips);setPlayhead(s.playhead);setZoom(s.zoom);return h.slice(0,-1)})},[clips,playhead,zoom]);
 const redo=useCallback(()=>{setFuture(f=>{const s=f[0];if(!s)return f;setHistory(h=>[...h,{clips:clips.map(c=>({...c})),playhead,zoom}]);setClips(s.clips);setPlayhead(s.playhead);setZoom(s.zoom);return f.slice(1)})},[clips,playhead,zoom]);
 const split=useCallback(()=>{const c=clips.find(x=>x.id===selected);if(!c||playhead<=c.start+MIN||playhead>=c.start+c.duration-MIN)return;save();const a={...c,id:id(),duration:playhead-c.start},b={...c,id:id(),start:playhead,duration:c.start+c.duration-playhead};setClips(cs=>cs.flatMap(x=>x.id===c.id?[a,b]:[x]));setSelected(b.id)},[clips,selected,playhead,save]);
 useEffect(()=>{if(!playing)return;let r=0;const tick=(n:number)=>{const d=Math.min(.05,(n-last.current)/1000);last.current=n;setPlayhead(p=>p+d>=total?0:p+d);r=requestAnimationFrame(tick)};last.current=performance.now();r=requestAnimationFrame(tick);return()=>cancelAnimationFrame(r)},[playing,total]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();return}if(mod&&e.key.toLowerCase()==="y"){e.preventDefault();redo();return}if(e.key===" "&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();setPlaying(p=>!p)}if(e.key.toLowerCase()==="b"){e.preventDefault();setTool("razor")}if(e.key.toLowerCase()==="v"){e.preventDefault();setTool("select")}if(e.key==="ArrowLeft"){e.preventDefault();setPlayhead(p=>Math.max(0,p-(e.shiftKey?1:1/FPS)))}if(e.key==="ArrowRight"){e.preventDefault();setPlayhead(p=>Math.min(total,p+(e.shiftKey?1:1/FPS)))}if((e.key==="Delete"||e.key==="Backspace")&&selected){e.preventDefault();save();setClips(cs=>cs.filter(c=>c.id!==selected));setSelected("")}};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[undo,redo,total,selected,save]);
 const importFiles=(fs:FileList|null)=>{if(!fs?.length)return;save();const add=Array.from(fs).map((f,i)=>{const audio=f.type.startsWith("audio")||/\\.(wav|mp3|aac|m4a)$/i.test(f.name),track=audio?1:0,start=Math.max(0,...clips.filter(c=>c.track===track).map(c=>c.start+c.duration))+.15*i;return{id:id(),track,kind:audio?"audio":"video" as Kind,name:f.name,start,duration:5,color:colors[(clips.length+i)%colors.length],url:URL.createObjectURL(f)}});setClips(c=>[...c,...add]);setSelected(add[0]?.id||"")};
 const wheel=(e:React.WheelEvent)=>{if(!e.ctrlKey&&Math.abs(e.deltaY)<Math.abs(e.deltaX))return;e.preventDefault();setZoom(z=>Math.max(20,Math.min(180,z*(e.deltaY>0?.9:1.1))))};
 return <div className="app">
  <header className="top"><div className="brand"><b>Z</b><strong>Z3treno</strong><small>PRO NLE</small></div><span className="title">Z3treno — Untitled Project</span><button onClick={()=>input.current?.click()}>Import</button><button>Save</button><button className="accent">Export</button></header>
  <main className="workspace">
   <aside className="media"><div className="tabs"><b>MEDIA</b><span>EFFECTS</span><span>TRANSITIONS</span></div><p>▾ Master</p><div className="grid">{clips.filter(c=>c.track===0).map(c=><button className={selected===c.id?"card selected":"card"} onClick={()=>setSelected(c.id)} key={c.id}><div style={{background:c.color}}>▶</div><small>{c.name}</small></button>)}<button className="card" onClick={()=>input.current?.click()}><div className="empty">＋</div><small>Import media</small></button></div></aside>
   <section className="viewer"><div className="bar"><span>MASTER VIEWER</span><span>{tc(playhead)}</span><span>1920×1080 · 30 FPS</span></div><div className="canvas"><div className="scene"><div className="road"/><strong>Z3</strong></div></div><div className="transport"><button onClick={()=>setPlayhead(0)}>⏮</button><button onClick={()=>setPlayhead(p=>Math.max(0,p-1/FPS))}>◀</button><button className="play" onClick={()=>setPlaying(p=>!p)}>{playing?"Ⅱ":"▶"}</button><button onClick={()=>setPlayhead(p=>Math.min(total,p+1/FPS))}>▶</button><button onClick={()=>setPlayhead(total)}>⏭</button><code>{tc(playhead)}</code></div></section>
   <aside className="inspector"><h3>INSPECTOR</h3><section><label>TRANSFORM</label><Row name="Position X" value="0"/><Row name="Position Y" value="0"/><Row name="Scale" value="1.00"/><Row name="Rotation" value="0°"/></section><section><label>CROPPING</label><Row name="Left" value="0"/><Row name="Right" value="0"/><Row name="Top" value="0"/><Row name="Bottom" value="0"/></section><section><label>COMPOSITE</label><Row name="Opacity" value="100%"/><Row name="Blend" value="Normal"/></section></aside>
  </main>
  <section className="timeline"><div className="tlbar"><div><button className={tool==="select"?"on":""} onClick={()=>setTool("select")}>↖ Select</button><button className={tool==="razor"?"on":""} onClick={()=>setTool("razor")}>✂ Razor</button><button onClick={undo} disabled={!history.length}>↶</button><button onClick={redo} disabled={!future.length}>↷</button></div><b>TIMELINE 01 · {tc(total)}</b><div className="zoom"><span>−</span><input type="range" min="20" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/><span>＋</span><button className={snap?"on":""} onClick={()=>setSnap(s=>!s)}>SNAP</button></div></div>
   <div className="tlbody"><div className="heads"><div className="rulerHead"/><div>V1 <small>VIDEO</small></div><div>A1 <small>AUDIO</small></div></div><div className="scroll" onWheel={wheel}><div className="ruler" style={{width:total*pps}}>{Array.from({length:Math.ceil(total)+1},(_,i)=><span style={{left:i*pps}} key={i}>{tc(i).slice(0,8)}</span>)}</div><div className="tracks" style={{width:total*pps}} onPointerDown={e=>{if((e.target as HTMLElement).closest(".clip"))return;const r=e.currentTarget.getBoundingClientRect();setPlayhead(Math.max(0,Math.min(total,(e.clientX-r.left)/pps)))}}>
    {[0,1].map(t=><div className="lane" key={t}>{clips.filter(c=>c.track===t).map(c=><div key={c.id} draggable className={selected===c.id?"clip selected":"clip"} style={{left:c.start*pps,width:Math.max(22,c.duration*pps),background:c.color}} onClick={e=>{e.stopPropagation();if(tool==="razor"){setSelected(c.id);split()}else setSelected(c.id)}} onDragStart={()=>setDrag(c.id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!drag)return;save();const r=e.currentTarget.parentElement?.getBoundingClientRect();const old=clips.find(x=>x.id===drag);if(r&&old){let start=Math.max(0,(e.clientX-r.left)/pps);if(snap)start=Math.round(start*4)/4;const d=start-old.start;setClips(cs=>cs.map(x=>x.id===drag?{...x,start:x.start+d}:x))}setDrag(null)}}><b>{c.name}</b><small>{c.kind.toUpperCase()} · {c.duration.toFixed(2)}s</small>{c.kind==="audio"&&<div className="wave">{Array.from({length:45},(_,i)=><i key={i} style={{height:(20+Math.abs(Math.sin(i*2.2))*70)+"%"}}/>)}</div>}</div>)}</div>)}<div className="playhead" style={{left:playhead*pps}}/></div></div></div>
  </section>
  <nav className="pages">{["Media","Cut","Edit","Fusion","Color","Fairlight","Deliver"].map((x,i)=><button className={x==="Edit"?"active":""} key={x}>{["⌂","▣","▤","◒","◉","♬","▦"][i]}<small>{x}</small></button>)}</nav>
  <input ref={input} hidden type="file" multiple accept="video/*,audio/*" onChange={e=>importFiles(e.target.files)}/>
 </div>
}